{% set name = "mleap" %}
{% set version = "0.15.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f698ce539917ce861659891661680b5814bf0d42e26c8f637431fb8c02c28f3

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - nose-exclude >=0.5.0
    - numpy >=1.8.2
    - pandas >=0.18.1
    - python
    - scikit-learn >=0.18.dev0
    - scipy >=0.13.0b1
    - six >=1.10.0

test:
  imports:
    - mleap
    - mleap.bundle
    - mleap.sklearn
    - mleap.sklearn.decomposition
    - mleap.sklearn.ensemble
    - mleap.sklearn.extensions
    - mleap.sklearn.feature_extraction
    - mleap.sklearn.preprocessing
    - mleap.sklearn.tree

about:
  home: https://github.com/combust/mleap/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: MLeap Python API

extra:
  recipe-maintainers:
    - xhochy
