travis:
  secure:
    BINSTAR_TOKEN: OnDxT4R0ulmF1IJ+4bOiOCSlbW4WOtDPwwFZ+6GqXbSYehZkXcmUfyqDc0xdbbH0N2BXFTcV/ZThkwxTnbh/TWV655PEDNTpTcr4OttOLTPj3as1eJqQ7kTnIMQzi+9qWGsbjXn3MLdTabeJj2eHPC2JgNOV+eIAg37OTosLUCboh3DmfJrmXjWYaLQZDpjLzULiHjJF2kQJkB39Dj4pGPjqPaD0MHfhBNju/07fLZWoLdYZgo5GwhD/h/GrHviYyXf69Tlbslm6tYJd+mIixs4N2zQrDLzOlNTiW212SjB2SchhcMQi2IofXaSTNJoE6SWC9GIhA7cvUiJ38AyJy8BTe/XridxnUV+NAeE4S8Uk9PH5BDPJB3I++6/JDQk85GFe4co4sSw9t5Kremmnzs15u4KKYrwpeHvwbNL7KCgi7/aZMWezfDVUoJAOIeUnnEfSJOZm3jtyzrPpMwmX3iQYdLCRkk85z4f3Y1u3C2s1ccNuG0LiXXGS1qGyHhKfXZ2SZVNUFXBQrqOjkR0AxkErZkBGHidyH40fgUqKZs2qW9drU8HRCi0qqt364H5KjYjpFEeWKzqOyECgsdkZD6nA3pZ3Qbau0Kd31kpT+XyAOSRtg3IZfrW6kT0G39rbSe6BHDqxS0ZP6qMmmlfPnKRKySU5P8ohKvXntWmzqYk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
